---
title: "Quiz 3 In Class"
output: html_document
---

“All work presented is my own. I have not communicated with or worked with anyone else on this quiz.”
Claire Dudley

Question 1 (5 points). Suppose you do the following:

You go to your GitHub site and make a change to the README file (adding a sentence, for example).
In R Studio, you update one of your .Rmd files, adding a line of code and commit the file.
You attempt to push the new file to your GitHub site.
Once you get to the third step, you’ll get an error when you try to push. Why? What do you need to do first before you make the push in Step 3?

Before you make the push, you need to pull to retrieve the changes you made to the README on your GitHub site. Without pulling, your Github site and your desktop project will not match so it will not allow you to push.

Question 2 (6 points). Give 2 advantages of using Git and GitHub. These must be advantages that we discussed in class (so you should not simply google “advantages of Git” and give the first two things that pop up).

One advantage of Git is that it makes it easier to collaborate on projects. Without Git, we would have to send code back and forth over email or text, which gets difficult. With Git we can work on the same files as long as we make sure to continue pulling before we push new changes.
Another advantage of Git is it is a form of saving our work to another space. We can feel safe knowing our work is not just on our desktop of one device, it is saved to something like a cloud accessible to other devices.

Question 3 (6 points). Choose 1 of the 12 principles of the ethical practice of data science that you think is the most difficult to execute. Give a short, possibly hypothetical, example that illustrates how that principle could be difficult to follow.

I think that #7, Recognize and mitigate bias in ourselves and in the data we use, is the most difficult to execute because it can be really difficult to detect our own bias. One example of this would be if we ran any sort of experiment, it's likely we have a personal bias already because we have a hypothesis or prediction for how the experiment will turn out. Due to this, we area already setting ourselves up to likely display any data we collect in a way that compliments and supports our hypothesis. We could do this by only focusing on parts of the data we collect, displaying our axis in certain ways, etc.

Question 4 (6 points). The authors of Data Feminism argued that data scientists should “embrace emotion,” not ignore it when building visuals. State the example that the authors used to show how emotion can be used to make a visual stronger. Then, give an argument against “embracing emotion.” In other words, give an argument that data visualizations should be devoid of emotion as much as possible, even if that’s not what you believe.

In Data Feminism, the example given to show how emotion can be used to make a visual stronger was through the gun violence interactive graph. Periscopic's graph is framed around loss, and is made to show how the victims of gun violence have names, ages, relationships, and should have had longer lives. This allows us to understand loss better than a bar chart without any humanizing qualities for the victims. 
One argument for data visualizations being devoid of emotion is how politicians have been using data recently. A lot of the graphics you see on Fox News and CNBC seem biased in one direction based on the data they are showing and the axis they choose to use. Both sides try to use emotion to convince the viewer to think in a certain way, instead of showing facts or information in a neutral way.


Question 5 (2 points). These two points are given for committing your .Rmd and .html files with a commit message correctly, and pushing them to your GitHub site.
