---
title: "Quiz 6 Take Home"
output: html_document
runtime: shiny
---

Quiz 6 Take-Home
Complete this Quiz in a .Rmd file. Submit a .Rmd and a knitted .html file to GitHub by the due date and time.

Statement of Integrity: Copy and paste the following statement and then sign your name (by typing it) on the line below.

“All work presented is my own, and I have followed all rules for collaboration.”
Claire Dudley

Collaboration Reminder: You may work with other students who are in our class on the take-home quiz, but you must list who you worked with at the top of your quiz. Write the name of any student(s) that you collaborated with in the space below this (ignore this if you did not collaborate with any students).
Kaden Pickering
Emil Zetterquist


Construct a Shiny app for any data set that we have worked with so far (besides SLU Majors and Tennis) or for any data set you used in STAT/DATA 234. Thirteen points will be given for Shiny apps that:

run,
have at least 2 different inputs,
have at least 1 plot output that looks presentable (e.g. appropriate labels, colour scale, and makes sense to construct).
Then, write a 2 sentence description about the purpose of your app (2 points).

```{r}
library(tidyverse)
library(here)
library(shiny)

nfl_df <- read_csv(here("data/standings.csv"))
nfl_df
var_choices <- names(nfl_df)[c(4:8)]

ui <- fluidPage(
  sidebarLayout(sidebarPanel(
    selectizeInput("teamchoice",
                   label = "Choose a Team", choices = levels(factor(nfl_df$team_name)),
                   selected = "Bills"),
    radioButtons("varchoice", label = "Choose a Statistic",
                 choices = var_choices)),
    mainPanel(plotOutput("scatterplot"))
  )
)

server <- function(input, output, session) {
  
  nfl_oneteam <- reactive({
    nfl_df %>% dplyr::filter(team_name == input$teamchoice)
  })

  
  
  
   
  output$scatterplot <- renderPlot({
    ggplot(data = nfl_oneteam(), aes(x = year, y = .data[[input$varchoice]])) + geom_line() + theme_minimal()
  })
  
  
}

shinyApp(ui, server)

```


Note that the in class version of the quiz will prompt you to use an app that has a sidebarLayout(). You do not need to use this function on the take-home quiz, but it may be helpful to use it for extra practice.

