---
title: "Quiz 2 in Class"
output: html_document
---


```{r}
library(tidyverse)
library(readxl)
library(here)

df <- read_excel(here("data/slu_graduates_17_21.xlsx"))

## fixes error in the data
df <- df %>% mutate(across(everything(),
                           .fns = ~replace(., . ==  "STATS" , "STAT")))
```

# Question 1
```{r}
majors_long <-
  df %>%
  pivot_longer(c("major1", "major2", "major3"),
               names_to = "discipline",
               values_to = "type") %>%
  filter(!is.na(type)) %>%
  group_by(type) %>%
  summarise(nstudents = n()) %>%
  arrange(desc(nstudents)) %>%
  slice(1:10) %>%
  ungroup() 
```

```{r}
majors_long %>%
   mutate(type = fct_reorder(type, nstudents)) %>%
ggplot(data = ., aes(x = type,
                                 y = nstudents)) + geom_point() + 
  geom_segment(aes(x = type,
                   xend = type,
                   y = 0,
                   yend = nstudents)) + 
  coord_flip() 
```

# Question 2
```{r}
stat_major <- 
  df %>%
  filter(major1 == "STAT" | major2 == "STAT" | major3 == "STAT")
```

```{r}
stat_major_long <-
  stat_major %>% 
  pivot_longer(c("minor1", "minor2", "minor3"),
               names_to = "Number",
               values_to = "Minor")
stat_sum <- stat_major_long %>%
  group_by(Minor) %>%
  summarise(count = n()) %>%
  filter(!is.na(Minor)) %>%
  filter(!Minor == "STAT") %>%
  mutate(Minor = fct_reorder(.f = Minor, .x = count))
```

```{r}
ggplot(data = stat_sum, aes(x = Minor, y = count)) + geom_col() + coord_flip()
```



